### ISSUE TITLE
Can't kill the Desktop

### ISSUE THREAD

**Issue by jorpilo** [avivace/dotfiles#11]
I have changed the i3 configuration but still when I open a new session the Plasma Desktop occupies the hole screen. 

After everything has loaded if I execute:

 i3-msg "exec --no-startup-id wmctrl -c Plasma for_window [title="Desktop - Plasma"] kill; floating enable; border none" 

Then the Desktop gets killed and I can see the i3 windows

**Comment by avivace** [comment]
So it works if you manually run the `wmctrl` command but not on i3 startup?

**Comment by jorpilo** [comment]
Yes, probably I am doing something wrong

**Comment by avivace** [comment]
Plasma is probably still starting when i3 runs that command, then.

Try with something like
```
exec "sh -c 'sleep 5; exec wmctrl -c Plasma for_window [title="Desktop - Plasma"] kill; floating enable; border none'"
```

Which delays the `wmctrl` command by 5 seconds.

**Comment by arlr** [comment]
I kill the desktop by modifying config file's code order and adding timer as you said. 

```
## Avoid tiling popups, dropdown windows from plasma
# for the first time, manually resize them, i3 will remember the setting for floating windows
for_window [class="plasmashell"] floating enable
for_window [class="Plasma"] floating enable, border none
for_window [title="plasma-desktop"] floating enable, border none
for_window [title="win7"] floating enable, border none
for_window [class="krunner"] floating enable, border none
for_window [class="Kmix"] floating enable, border none
for_window [class="Klipper"] floating enable, border none
for_window [class="Plasmoidviewer"] floating enable, border none

## Plasma Integration
# Try to kill the wallpaper set by Plasma (it takes up the entire workspace and hides everythiing)
exec --no-startup-id sleep 5 && wmctrl -c Plasma for_window [title="Desktop — Plasma"] kill, floating enable, border none
```
