### ISSUE TITLE
Login screen is being used as background

### ISSUE THREAD

**Issue by aDogCalledSpot** [avivace/dotfiles#14]
Once I log in, the taskbar loads up and I can use everything as intended. The only problem is that the background is simply the login screen with the password filled out.

Using `feh --bg-scale path/to/my/bgpic` in a console yields the desired result but it isn't happening at startup.

**Comment by aDogCalledSpot** [comment]
Using `exec --no-startup-id feh --bg-scale path/to/my/bgpic` in the i3 config worked

**Comment by avivace** [comment]
This started happening to me with the last `dist-upgrade`. Thank you for your solution, will add to the i3 configuration.
