### ISSUE TITLE
Alternatives to awesome-widgets

### ISSUE THREAD

**Issue by trev-dev** [avivace/dotfiles#15]
## Thank you so much for this repo and readme!
Unfortunately, things are looking a little ugly at awesome-widgets 
https://github.com/arcan1s/awesome-widgets

Are you still using this plasmoid with the latest plasma desktop (I use Arch, btw). If not, are you able to suggest whatever alternative you're using?

**Comment by avivace** [comment]
Oh hey! Thank you for the kind words!

Everything is going smooth for me (I've still an old version of `awesome-widgets` installed).

Can you provide some screenshots on what's happening?

**Comment by trev-dev** [comment]
I would, but like most Linux enthusiasts, I moved on haha. I'm ok with the widgets I've got. Let's call this issue as a point of reference for anyone who gets the current plugin and can't make it work.
