### ISSUE TITLE
Notification handling

### ISSUE THREAD

**Issue by jklmnn** [avivace/dotfiles#2]
I have stripped down your setup a bit for me, so I'm using only the i3 and compton config and plasmas env/wm.sh script. I have set up two machines with this and it mostly works fine. There are only two minor issues:
 - Plasma background isn't closing even though I have set `for_window [title="Desktop — Plasma"] kill; floating enable; border none`. This not a big Problem as I can close it with ctrl+shift+q.
 - Notifications. On one machine I have Plasma notifications and on one I have the i3 ones. Do you have any idea what decides which notifications should be used? I'd alyways like to have the Plasma ones.

**Comment by avivace** [comment]
> Plasma background isn't closing even though I have set for_window [title="Desktop — Plasma"] kill; floating enable; border none. This not a big Problem as I can close it with ctrl+shift+q.

Do you have the string `exec --no-startup-id wmctrl -c Plasma` too? Try running `wmctrl -c Plasma` in the terminal and see if it actually kills the wallpaper (maybe you don't have the `wmctrl` package?).

If none of the above works, maybe the name changed:
What version of Plasma are you on? (I'm still on 5.8.4) Use `xprop`, click on the background and check the `WM_NAME(STRING)`.

> Notifications. On one machine I have Plasma notifications and on one I have the i3 ones. Do you have any idea what decides which notifications should be used? I'd alyways like to have the Plasma ones.

i3 doesn't include any notification handling, maybe you have installed i3 from a package which includes a notification daemon or you have one preinstalled. Check if you have `dunst` installed.

**Comment by jklmnn** [comment]
I indeed had `dunst` installed, removing it brought the Plasma notifications back. It comes as recommended with `i3` in Debian.
Also `xprop` helped me to identify the window name, I had to use `_NET_WM_NAME(UTF8_STRING)`.
Thanks for your help!
