### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by bran** [avivace/dotfiles#20]
https://github.com/avivace/dotfiles/blob/2f6cdf6ecd5b9a53a7754141eb1376c5cf09039e/plasma/.config/plasma-workspace/env/wm.sh#L12

Is this ampersand supposed to be where it is?

**Comment by avivace** [comment]
It has been reported that `compton -b` may cause a display freeze.
I've never experienced it until recently, when I found out `&` doesn't cause this and may be a safer choice.

https://wiki.archlinux.org/index.php/compton
