### ISSUE TITLE
Just seeing gray screen

### ISSUE THREAD

**Issue by wonjoonSeol** [avivace/dotfiles#25]
![err](https://user-images.githubusercontent.com/22602022/62009414-d5683600-b199-11e9-9154-115d729eb663.png)
Screenshot doesn't show i3 bottom bar but it is there.

Fresh Installed Manjaro with KDE: 
_OS: Manjaro Linux x86_64 
Kernel: 4.19.60-1-MANJARO 
Packages: 1101 (pacman) 
Shell: zsh 5.7.1 
Resolution: 2560x1440 
DE: KDE
Theme: Breath [KDE], Breath [GTK2/3] 
Terminal: konsole 
Terminal Font: Noto Mono 10 
CPU: Intel i7-6700K (8) @ 4.200GHz 
GPU: NVIDIA GeForce GTX 980 
Memory: 1351MiB / 15978MiB_ 

i3-gaps window just appear gray like shown in the picture.
If I set floating windows it shows correctly but rest simply does not appear.

Steps I have done:
1. In i3/config:
```
## Plasma Integration
# Try to kill the wallpaper set by Plasma (it takes up the entire workspace and hides everythiing)
exec --no-startup-id wmctrl -c Plasma
for_window [title="Desktop — Plasma"] kill, floating enable, border none

## Avoid tiling popups, dropdown windows from plasma
# for the first time, manually resize them, i3 will remember the setting for floating windows
for_window [class="plasmashell"] floating enable
for_window [class="Plasma"] floating enable, border none
for_window [title="plasma-desktop"] floating enable, border none
for_window [title="win7"] floating enable, border none
for_window [class="krunner"] floating enable, border none
for_window [class="Kmix"] floating enable, border none
for_window [class="Klipper"] floating enable, border none
for_window [class="Plasmoidviewer"] floating enable, border none
```

2. wm.sh
```
export KDEWM=/usr/local/bin/i3
compton & --config ~/.config/compton/compton.conf  (Tried without this as well)
```

3. compton.conf: Everything. But in particular I tried:
backend = "glx", "xrender"
vsync on and off.

4. Killing desktop 
`i3-msg "exec --no-startup-id wmctrl -c Plasma for_window [title="Desktop - Plasma"] kill; floating enable; border none"`
No difference, still gray.
 
Opening any new programs shows in the KDE top bar but shows nothing on screen.

Any advice would be appreciated.

**Comment by avivace** [comment]
This is probably a plasma panel or the splash not getting killed.
Some suggestions and things to try:

- Try` mod+maiusc+q` while focusing the gray area to try and exit it with i3.
- Do you have wmctrl installed? Otherwise the i3-msg line won't work
- If you manage to open a terminal, use `xprop` to identify the gray window and try to kill it with wmctrl.

**Comment by wonjoonSeol** [comment]
Many thanks for the suggestion,
I have actually moved to Arch with pure i3-gaps (following Luke Smith's dotfiles). 

Quite happy with the transition will report back when my new laptop arrives and install your version there with this provided suggestion!

Closed for now.
