### ISSUE TITLE
How to fix white box in plasma bar?

### ISSUE THREAD

**Issue by Zackhardtoname** [avivace/dotfiles#33]
I noticed many integrations of i3 and plasma like mine and [this point in this walkthrough video](https://youtu.be/OSMX25ySKRA?t=4717) have white boxes instead of apps like below:
![image](https://user-images.githubusercontent.com/25935197/100497060-f42c6300-3126-11eb-8df8-e99fd240d753.png)

On hovering:
The right visuable ones are the ones I pined.
![image](https://user-images.githubusercontent.com/25935197/100497075-073f3300-3127-11eb-97f9-749c42dbcd11.png)

It looks like you got folders for apps. That's really cool and I wonder how to do it! Thanks!

**Comment by avivace** [comment]
Hi @Zackhardtoname, I think this is related to the "Pager" widget configuration. Try to right click on it, first option should be the icon one.
![image](https://user-images.githubusercontent.com/14352721/101296474-2410f000-3824-11eb-9ab1-75b597e81bf3.png)

**Comment by Zackhardtoname** [comment]
That worked! 
Now the only problem I have is that sometimes the entire KDE taskbar row doesn't appear (randomly and it persists until I restart to get it back) and only my i3 bar shows. I googled but couldn't find any command to use to invoke the bar.

Have you ever encountered that?  Thank you so much!!

**Comment by avivace** [comment]
> That worked!
> Now the only problem I have is that sometimes the entire KDE taskbar row doesn't appear (randomly and it persists until I restart to get it back) and only my i3 bar shows. I googled but couldn't find any command to use to invoke the bar.
> 
> Have you ever encountered that? Thank you so much!!

Never had this kind of issue. You should open `plasmashell` from a shell and try to look at what happens when it doesn't render (or check logs)

**Comment by Zackhardtoname** [comment]
yeah not sure why but it works much better on my desktop than my laptop.

Now I have no problem except sometimes upon boot, Chrome does not exactly fit into any container or window (like it could take some space over the taskbar).

I kind of just have to kill it and relaunch it. Other than that, it's working really nicely!

**Comment by avivace** [comment]
That's great, I'm glad to hear that! I'm gonna close this, when you have more information (or logs) on that feel free to open another issue
