### ISSUE TITLE
Shell Popup doesn't Show Up in Dual Stacked Monitors when They are in the Lower One

### ISSUE THREAD

**Issue by Zackhardtoname** [avivace/dotfiles#36]
I found out if it works if the shell one is set to be the top one in the software configuration but it doesn't otherwise.
Not sure if anything is wrong.

A screenshot across 2 monitors with the desired configuration 
![image](https://user-images.githubusercontent.com/25935197/110279306-e51b4380-7fa6-11eb-8207-f4b83ec71edd.png)
All I get is this black box in the middle of the bottom screen.

**Comment by Zackhardtoname** [comment]
Somehow this is fixed after my latest system-wide package update. Not sure exactly what fixed it though.

**Comment by avivace** [comment]
Thanks for the heads-up @Zackhardtoname ! Glad it's fixed
