### ISSUE TITLE
Display manager wiring? ssdm?

### ISSUE THREAD

**Issue by jcrben** [avivace/dotfiles#6]
> You will still use the Plasma session with startx, so set your login manager accordingly.

Could you elaborate on your exact steps? I have my `sddm.conf` in my dotfiles - what display manager are you using? I'm pretty new to KDE / i3 as I've been using macOS for the past few years. I imagine I could figure it out, but hoping to skip the trial and error...

I wonder if the blog post linked in the README might have some details, but alas, it's a dead link: https://avivace.com/blog/debian-and-kde-plasma.html - and apparently the Internet Archive didn't pick it up

I noticed https://avivace.com/blog/linux.html but it doesn't seem quite the same.

UPDATE: discovered that one thing tripping me up was autologin, so I was skipping the chance to select i3... still messing around with it.

**Comment by avivace** [comment]
Thank you for noticing the dead link, I corrected it.

I am using SDDM as login manager, but its configuration is missing here (I'm gonna fix this in the next days, thank you again).

[Here](https://wiki.archlinux.org/index.php/SDDM#Configuration) you can read how you can customize SDDM. To start plasma with the autologin, just look in `/usr/share/xsessions/` for the available sessions, you should find a plasma entry (usually `plasma.desktop`). Set it as the "Session" value in `/etc/sddm.conf.d/autologin.conf` and you should be good to go.

OR, disable the autologin and the next time you have to login you'll see a selector for the desired session.

**Comment by jcrben** [comment]
Hey @avivace - thanks for pointing me to the SDDM docs, but I'd already messed around with them. I put that UPDATE because my sddm autologin was actually causing issues. It's not entirely clear how KDE and i3 work together as there doesn't seem to be much official documentation on their integration (https://github.com/avivace/dotfiles/blob/master/X/.xinitrc#L12). I actually found that running them both side by side ended up causing too many bugs (especially on the bleeding edge), so I'll wait for Sway / wlroots, which is starting to work with the KDE team.

Anyway, I eventually ended up going with nixos (https://nixos.org/) where I just have to put this in my `configuration.nix`:

```
  # Enable the KDE Desktop Environment.
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;

  # enable i3
  services.xserver.windowManager.i3.enable = true;
```

My system isn't really worth sharing (still messy and stuff), but you can see a bunch of examples over at https://nixos.wiki/wiki/Configuration_Collection
