### ISSUE TITLE
Make "Desktop — Plasma" run as Wallpaper

### ISSUE THREAD

**Issue by daviddavo** [avivace/dotfiles#8]
Hello, I've come to propose an idea, what if instead of killing the plasma desktop you keep it as 'background'? Like how VLC can play a video as background/wallpaper. I'm pretty sure there should be a program/command/thing to do this, even if you have to set the position of the background window manually.

Do you know any program that can do this?

Btw, your set-up works great on Manjaro and Arch

**Comment by avivace** [comment]
I'm glad the setup works for you!

What would be the upsides of having ksplash as "background"? Widgets, maybe? A part from that it doesn't really offer something a part from the wallpaper function.

**Comment by RomanHargrave** [comment]
@daviddavo this functionality is known as the root window.
